# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19fccccb2f99baf7535e279d3cd2c0fc3eb8acbf6b56e6155505189eaf4a168be77341c6f77b8bc5515429ba7e632ca41f016aa36653086a17a60f5c9e32786

test:
  secret_key_base: 9fd6a3d7af07106851503ecd516398fc4ae442ca5a813579f7e64e40471f161f35733bcd6e9e120d397b53712529c83262bf851a3ff84b74b12239e086620c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
