# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 998410b527730a453b55e4ca671dea9b9147e883245e472982c8078a66286b2592b6a56449d8b65ed4c23ee784a4663a96c55a596219e5fa4a4bfc9cb02a342a

test:
  secret_key_base: 3d147039a586a513d0c35935225e3a12e59e4b9b60868086503b4d3cc4d6c74368826bec98261f635545fb7e80ff2df70ee8eb292fe6239b19896b474dfb062a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
